name: Roberta Pesce
favicon: null
layout_spectrum: 0.460913916118443
typography_spectrum: 0.3052699323743582
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2785131314303726
  lightness: 0.17808341374620795
  saturation: 0.9520197666715831
  rhythmicContrast: 0.14863221533596516
purpose: []
